//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllogin
    {
        public int Uid { get; set; }
        public long BadgeNumber { get; set; }
        public string UserName { get; set; }
        public string pass { get; set; }
        public Nullable<System.DateTime> endloginTime { get; set; }
        public string persianName { get; set; }
        public bool UEnable { get; set; }
    }
}
